### ISSUE TITLE
🐞 [FIX] 과제 제안/프로젝트 문의 api 변경 요청 

### ISSUE THREAD

**Issue by hynseok** [SystemConsultantGroup/S-top-backend#112]
## 요청사항
[과제 제안/프로젝트 문의] 단건 조회 api에서 
해당 [과제 제안/프로젝트 문의]가 답변이 등록되었는지 확인할 수 있는 필드가 있었으면 좋겠습니다.

## 설명
1. 프론트 페이지에서는 [과제 제안/프로젝트 문의]를 조회하고, 답변을 등록/수정하는 페이지가 하나의 페이지로 구성되어 있습니다.
2. 답변 수정을 위해서는 기존에 등록된 답변을 페치해야합니다.
3. 답변이 등록된 [과제 제안/프로젝트 문의]만 페치하는 것이 불필요한 요청을 줄이는 것 같습니다.

현재는 답변이 등록되었는지 확인하려면 답변에 대한 get 요청을 한번 보내서
등록된 답변이 없다는 오류를 보고 확인할 수 있습니다.

테이블을 확인해보니 확인할 수 있는 필드값이 없어서 데이터베이스에도 컬럼을 추가해야할 것 같습니다.

### 🏗 Reproduction

.

### 🪵 Logs

```shell
.
```

### 🖥 Environment ️

.

### ✔️CheckList

- [X] 관련 Issue 가 이미 존재하는 지 확인해보셨나요?
- [X] Assignees 설정
- [X] Labels 설정

**Comment by yesjuhee** [comment]
데이터베이스 칼럼 추가 없이 응답 DTO에 boolean 필드 하나 추가하는게 좋을 것 같습니다!

@shj1081 @jcy0308
