### ISSUE TITLE
🐞 [BUG] 공지사항/이벤트공지사항 조회 시 정렬 기능 미적용

### ISSUE THREAD

**Issue by yesjuhee** [SystemConsultantGroup/s-top-backend#80]
### 📖 Description

`getNotices`, `getEventNotices`에서 쿼리 파라미터로 `sort`를 사용할 수 있도록 수정해야 합니다.

### 🏗 Reproduction

Pageable을 사용하면 `sort=title` 이런 식으로 넣어줬을 때 정렬을 자동 적용하는 기능이 있는데 현재 API로는 정렬 기능이 사용이 안됩니다.
아마 처음 API문서에 sort 파라미터가 없어서 고려가 안된 것 같은데 프론트에서 필요하다고 요청이 와서 추가해야할 것 같습니다!
서비스에서 `adjustedPageable`을 생성할 때 `pageable.getSort()`를 포함해서 생성하는 방식으로 수정하면 될 것 같습니다.

### ✔️CheckList

- [X] 관련 Issue 가 이미 존재하는 지 확인해보셨나요?
- [X] Assignees 설정
- [X] Labels 설정

**Comment by shj1081** [comment]
맡고있는 모든 페이지 리스트 형태로 조회하는 api에 해당기능을 추가하는 것이 좋을까요?
