### ISSUE TITLE
🐞 [BUG] Video API 문서 관련 버그 

### ISSUE THREAD

**Issue by 2tle** [SystemConsultantGroup/s-top-backend#83]
### 📖 Description

API Restdocs에 대담 영상 및 잡페어 인터뷰에 관심 여부(favorite)이 보이지 않음

### 🏗 Reproduction

1.
2.
3.

### ✔️CheckList

- [X] 관련 Issue 가 이미 존재하는 지 확인해보셨나요?
- [X] Assignees 설정
- [X] Labels 설정

**Comment by yesjuhee** [comment]
PR #81 에서 수정했습니다!
